
export interface Country {
    name: string;
    code: string; // ISO 3166-1 alpha-2
    phone: string;
    phoneRegex?: RegExp;
}

export const countries: Country[] = [
    { name: "United States", code: "US", phone: "+1", phoneRegex: /^\d{10}$/ },
    { name: "United Kingdom", code: "GB", phone: "+44", phoneRegex: /^\d{10}$/ },
    { name: "United Arab Emirates", code: "AE", phone: "+971", phoneRegex: /^\d{9}$/ },
    { name: "India", code: "IN", phone: "+91", phoneRegex: /^\d{10}$/ },
    { name: "Afghanistan", code: "AF", phone: "+93" },
    { name: "Albania", code: "AL", phone: "+355" },
    { name: "Algeria", code: "DZ", phone: "+213" },
    { name: "Andorra", code: "AD", phone: "+376" },
    { name: "Angola", code: "AO", phone: "+244" },
    { name: "Argentina", code: "AR", phone: "+54" },
    { name: "Armenia", code: "AM", phone: "+374" },
    { name: "Australia", code: "AU", phone: "+61" },
    { name: "Austria", code: "AT", phone: "+43" },
    { name: "Azerbaijan", code: "AZ", phone: "+994" },
    { name: "Bahamas", code: "BS", phone: "+1-242" },
    { name: "Bahrain", code: "BH", phone: "+973" },
    { name: "Bangladesh", code: "BD", phone: "+880" },
    { name: "Belarus", code: "BY", phone: "+375" },
    { name: "Belgium", code: "BE", phone: "+32" },
    { name: "Belize", code: "BZ", phone: "+501" },
    { name: "Benin", code: "BJ", phone: "+229" },
    { name: "Bhutan", code: "BT", phone: "+975" },
    { name: "Bolivia", code: "BO", phone: "+591" },
    { name: "Bosnia and Herzegovina", code: "BA", phone: "+387" },
    { name: "Botswana", code: "BW", phone: "+267" },
    { name: "Brazil", code: "BR", phone: "+55" },
    { name: "Brunei", code: "BN", phone: "+673" },
    { name: "Bulgaria", code: "BG", phone: "+359" },
    { name: "Burkina Faso", code: "BF", phone: "+226" },
    { name: "Cambodia", code: "KH", phone: "+855" },
    { name: "Cameroon", code: "CM", phone: "+237" },
    { name: "Canada", code: "CA", phone: "+1", phoneRegex: /^\d{10}$/ },
    { name: "Central African Republic", code: "CF", phone: "+236" },
    { name: "Chad", code: "TD", phone: "+235" },
    { name: "Chile", code: "CL", phone: "+56" },
    { name: "China", code: "CN", phone: "+86", phoneRegex: /^\d{11}$/ },
    { name: "Colombia", code: "CO", phone: "+57" },
    { name: "Congo, Democratic Republic", code: "CD", phone: "+243" },
    { name: "Congo, Republic of the", code: "CG", phone: "+242" },
    { name: "Costa Rica", code: "CR", phone: "+506" },
    { name: "Croatia", code: "HR", phone: "+385" },
    { name: "Cuba", code: "CU", phone: "+53" },
    { name: "Cyprus", code: "CY", phone: "+357" },
    { name: "Czech Republic", code: "CZ", phone: "+420" },
    { name: "Denmark", code: "DK", phone: "+45" },
    { name: "Djibouti", code: "DJ", phone: "+253" },
    { name: "Dominican Republic", code: "DO", phone: "+1-809" },
    { name: "Ecuador", code: "EC", phone: "+593" },
    { name: "Egypt", code: "EG", phone: "+20" },
    { name: "El Salvador", code: "SV", phone: "+503" },
    { name: "Estonia", code: "EE", phone: "+372" },
    { name: "Ethiopia", code: "ET", phone: "+251" },
    { name: "Fiji", code: "FJ", phone: "+679" },
    { name: "Finland", code: "FI", phone: "+358" },
    { name: "France", code: "FR", phone: "+33" },
    { name: "Georgia", code: "GE", phone: "+995" },
    { name: "Germany", code: "DE", phone: "+49" },
    { name: "Ghana", code: "GH", phone: "+233" },
    { name: "Greece", code: "GR", phone: "+30" },
    { name: "Guatemala", code: "GT", phone: "+502" },
    { name: "Honduras", code: "HN", phone: "+504" },
    { name: "Hong Kong", code: "HK", phone: "+852" },
    { name: "Hungary", code: "HU", phone: "+36" },
    { name: "Iceland", code: "IS", phone: "+354" },
    { name: "Indonesia", code: "ID", phone: "+62" },
    { name: "Iran", code: "IR", phone: "+98" },
    { name: "Iraq", code: "IQ", phone: "+964" },
    { name: "Ireland", code: "IE", phone: "+353" },
    { name: "Israel", code: "IL", phone: "+972" },
    { name: "Italy", code: "IT", phone: "+39" },
    { name: "Jamaica", code: "JM", phone: "+1-876" },
    { name: "Japan", code: "JP", phone: "+81" },
    { name: "Jordan", code: "JO", phone: "+962" },
    { name: "Kazakhstan", code: "KZ", phone: "+7" },
    { name: "Kenya", code: "KE", phone: "+254" },
    { name: "Kuwait", code: "KW", phone: "+965" },
    { name: "Latvia", code: "LV", phone: "+371" },
    { name: "Lebanon", code: "LB", phone: "+961" },
    { name: "Libya", code: "LY", phone: "+218" },
    { name: "Lithuania", code: "LT", phone: "+370" },
    { name: "Luxembourg", code: "LU", phone: "+352" },
    { name: "Malaysia", code: "MY", phone: "+60" },
    { name: "Maldives", code: "MV", phone: "+960" },
    { name: "Malta", code: "MT", phone: "+356" },
    { name: "Mexico", code: "MX", phone: "+52" },
    { name: "Monaco", code: "MC", phone: "+377" },
    { name: "Mongolia", code: "MN", phone: "+976" },
    { name: "Montenegro", code: "ME", phone: "+382" },
    { name: "Morocco", code: "MA", phone: "+212" },
    { name: "Myanmar", code: "MM", phone: "+95" },
    { name: "Nepal", code: "NP", phone: "+977" },
    { name: "Netherlands", code: "NL", phone: "+31" },
    { name: "New Zealand", code: "NZ", phone: "+64" },
    { name: "Nicaragua", code: "NI", phone: "+505" },
    { name: "Nigeria", code: "NG", phone: "+234" },
    { name: "North Korea", code: "KP", phone: "+850" },
    { name: "North Macedonia", code: "MK", phone: "+389" },
    { name: "Norway", code: "NO", phone: "+47" },
    { name: "Oman", code: "OM", phone: "+968" },
    { name: "Pakistan", code: "PK", phone: "+92" },
    { name: "Panama", code: "PA", phone: "+507" },
    { name: "Paraguay", code: "PY", phone: "+595" },
    { name: "Peru", code: "PE", phone: "+51" },
    { name: "Philippines", code: "PH", phone: "+63" },
    { name: "Poland", code: "PL", phone: "+48" },
    { name: "Portugal", code: "PT", phone: "+351" },
    { name: "Qatar", code: "QA", phone: "+974" },
    { name: "Romania", code: "RO", phone: "+40" },
    { name: "Russia", code: "RU", phone: "+7" },
    { name: "Saudi Arabia", code: "SA", phone: "+966" },
    { name: "Senegal", code: "SN", phone: "+221" },
    { name: "Serbia", code: "RS", phone: "+381" },
    { name: "Singapore", code: "SG", phone: "+65" },
    { name: "Slovakia", code: "SK", phone: "+421" },
    { name: "Slovenia", code: "SI", phone: "+386" },
    { name: "Somalia", code: "SO", phone: "+252" },
    { name: "South Africa", code: "ZA", phone: "+27" },
    { name: "South Korea", code: "KR", phone: "+82" },
    { name: "Spain", code: "ES", phone: "+34" },
    { name: "Sri Lanka", code: "LK", phone: "+94" },
    { name: "Sudan", code: "SD", phone: "+249" },
    { name: "Sweden", code: "SE", phone: "+46" },
    { name: "Switzerland", code: "CH", phone: "+41" },
    { name: "Syria", code: "SY", phone: "+963" },
    { name: "Taiwan", code: "TW", phone: "+886" },
    { name: "Tanzania", code: "TZ", phone: "+255" },
    { name: "Thailand", code: "TH", phone: "+66" },
    { name: "Turkey", code: "TR", phone: "+90" },
    { name: "Uganda", code: "UG", phone: "+256" },
    { name: "Ukraine", code: "UA", phone: "+380" },
    { name: "Uruguay", code: "UY", phone: "+598" },
    { name: "Uzbekistan", code: "UZ", phone: "+998" },
    { name: "Venezuela", code: "VE", phone: "+58" },
    { name: "Vietnam", code: "VN", phone: "+84" },
    { name: "Yemen", code: "YE", phone: "+967" },
    { name: "Zambia", code: "ZM", phone: "+260" },
    { name: "Zimbabwe", code: "ZW", phone: "+263" },
].sort((a,b) => a.name.localeCompare(b.name));

export const getCountry = (code?: string | null): Country | undefined => {
    if (!code) return countries.find(c => c.code === 'US');
    return countries.find(c => c.code.toLowerCase() === code.toLowerCase());
}
